apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-master 
  labels:
    app: druid
    service: druid-master 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid
      service: druid-master 
  template:
    metadata:
      name: druid-master 
      labels:
        app: druid
        service: druid-master 
    spec:
      containers:
        - name: druid-master 
          image: tglanz/druid-master
          imagePullPolicy: IfNotPresent
          ports:
            - name: coordinator 
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: druid-master 
  labels:
    app: druid
    service: druid-master 
spec:
  ports:
    - port: 8081
      targetPort: 8081 
  selector:
    app: druid
    service: druid-master 
