apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-query 
  labels:
    app: druid
    service: druid-query 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid
      service: druid-query 
  template:
    metadata:
      name: druid-query 
      labels:
        app: druid
        service: druid-query 
    spec:
      containers:
        - name: druid-query 
          image: tglanz/druid-query
          imagePullPolicy: IfNotPresent
          ports:
            - name: router
              containerPort: 8888 
            - name: broker
              containerPort: 8082 
---
apiVersion: v1
kind: Service
metadata:
  name: druid-query 
  labels:
    app: druid
    service: druid-query 
spec:
  ports:
    - port: 8888 
      targetPort: 8888 
      name: router
    - port: 8082
      targetPort: 8082
      name: broker
  selector:
    app: druid
    service: druid-query 
